---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab
  name: gitlab-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab
  name: gitlab-logs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab
  name: gitlab-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: gitlab
  name: gitlab-backups
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  labels:
#    app: gitlab
#  name: gitlab-secrets
#spec:
#  accessModes:
#  - ReadWriteOnce
#  resources:
#    requests:
#      storage: 50Mi